" Color scheme
" https://github.com/michalbachowski/vim-wombat256mod
"color wombat256mod
color desert
"set t_Co=256

" UI
syntax on
highlight ColorColumn ctermbg=darkgrey
highlight SpellBad cterm=underline ctermbg=none ctermfg=red
highlight ExtraWhitespace ctermbg=red guibg=red
autocmd ColorScheme * highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
"set breakindent
"set breakindentopt=sbr
set colorcolumn=80
set cursorline
set lazyredraw
set linebreak
set nowrap
set number
set ruler
set showbreak=>>>
set spell
set splitbelow
set splitright
set wildmenu

" Search
highlight Search cterm=none ctermbg=grey ctermfg=black
set hlsearch
set ignorecase
set incsearch
set smartcase

" Backup and Swap
set nobackup
set nowritebackup
set swapfile
set dir=~/.vim/swap//
