name: BuildChecks

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.8'
      - name: PrepareEnv
        run: python -mpip install pipenv
      - name: Install Dependencies
        run: pipenv sync --dev
      - name: Check Tag Is New
        run: '[[ -z $(git tag -l | grep -E "^$(cat VERSION)$") ]]'
